# Server settings

server_hostname: "baobab-staging"

# Plone settings
plone_target_path: "/opt/baobab"
plone_var_path: "/var/local/Plone"
plone_instance_name: "{{ server_hostname }}"
plone_initial_password: 123qwe


#####################################
# DO NOT TOUCH THE STUFF BELOW HERE #
#####################################
plone_version: '4.3.11'
plone_python_version: '2.7'
plone_install_zeoserver: yes
plone_backup_path: no
plone_create_site: no
plone_buildout_cache_url: https://launchpad.net/plone/{{ plone_major_version }}/4.3.18/+download/buildout-cache.tar.bz2
plone_additional_eggs:
  - bika.lims
  - baobab.lims
  - graphite.theme
plone_buildout_extra: |
  develop =
    src/bika.lims
    src/baobab.lims
    src/graphite.theme

plone_extension_profiles:
    - mr.developer

plone_sources: 
  - "bika.lims = git git://github.com/zipho/bika.lims.git pushurl=git@github.com:zipho/bika.lims.git branch=master"
  - "baobab.lims = git git://github.com/zipho/baobab.lims.git pushurl=git@github.com:zipho/baobab.lims.git branch=master"
  - "graphite.theme = git git://github.com/zipho/graphite.theme.git pushurl=git@github.com:zipho/graphite.theme.git"

plone_client_base_port: 8080
plone_additional_versions:
  - "cairocffi = 0.4"

nginx_enable: true
nginx_main_template_enable: true
nginx_http_template_enable: true

nginx_http_template:
  default:
    template_file: http/default.conf.j2
    conf_file_name: default.conf
    conf_file_location: /etc/nginx/conf.d/
    port: 80
    server_name: "{{ server_hostname }}"
    error_page: /usr/share/nginx/html
    https_redirect: false
    autoindex: false
    listen: 
      listen_localhost:
        ip: localhost # Wrap in square brackets for IPv6 addresses
        port: 8081
        opts: []
    # ssl:
    #   cert: /etc/ssl/certs/default.crt
    #   key: /etc/ssl/private/default.key
    reverse_proxy:
      locations:
        backend:
          location: /
          proxy_pass: http://app_servers
      health_check_plus: false
    upstreams:
      app_servers:
        name: app_servers
        lb_method: least_conn
        zone_name: backend
        zone_size: 64k
        sticky_cookie: false
        servers:
          baobab1:
            address: localhost
            port: 8080
            weight: 1
            health_check: max_fails=1 fail_timeout=10s
          baobab2:
            address: localhost
            port: 8081
            weight: 1
            health_check: max_fails=1 fail_timeout=10s