# Server settings

server_hostname: "stage.baobablims.org"

# Plone settings
plone_target_path: "/opt/baobab"
plone_var_path: "/var/local/Plone"
plone_instance_name: "{{ server_hostname }}"
plone_initial_password: 123qwe


#####################################
# DO NOT TOUCH THE STUFF BELOW HERE #
#####################################
plone_version: '4.3.11'
plone_python_version: '2.7'
plone_install_zeoserver: yes
plone_backup_path: no
plone_create_site: no
plone_buildout_cache_url: https://launchpad.net/plone/{{ plone_major_version }}/4.3.18/+download/buildout-cache.tar.bz2
plone_additional_eggs:
  - bika.lims
  - baobab.lims
  - graphite.theme
plone_buildout_extra: |
  develop =
    src/bika.lims
    src/baobab.lims
    src/graphite.theme

plone_extension_profiles:
    - mr.developer

plone_sources: 
  - "bika.lims = git git://github.com/zipho/bika.lims.git pushurl=git@github.com:zipho/bika.lims.git branch=reports"
  - "baobab.lims = git git://github.com/zipho/baobab.lims.git pushurl=git@github.com:zipho/baobab.lims.git branch=master"
  - "graphite.theme = git git://github.com/zipho/graphite.theme.git pushurl=git@github.com:zipho/graphite.theme.git branch=master"

plone_client_base_port: 8080
plone_additional_versions:
  - "cairocffi = 0.4"
  - "Products.AdvancedQuery = 3.0.4"
  - "xlsxwriter = 1.2.0"

nginx_enable: true
nginx_main_template_enable: true
nginx_http_template_enable: true

nginx_http_template:
  default:
    template_file: http/default.conf.j2
    conf_file_name: default.conf
    conf_file_location: /etc/nginx/conf.d/
    port: 80
    server_name: "{{ server_hostname }}"
    error_page: /usr/share/nginx/html
    https_redirect: false
    autoindex: false
    # listen: 
    #   listen_localhost:
    #     ip: localhost # Wrap in square brackets for IPv6 addresses
    #     port: 8081
    #     opts: []
    # ssl:
    #   cert: /etc/ssl/certs/default.crt
    #   key: /etc/ssl/private/default.key
    add_headers:
      x_frame_options:
        name: X-Frame-Options
        value: SAMEORIGIN
        always: true
      strict_transport_security:
        name: Strict-Transport-Security
        value: max-age=15768000; includeSubDomains
        always: true
      x_xss_protection:
        name: X-XSS-Protection
        value: 1; mode=block
        always: true
      content_security_policy_report_only:
        name: Content-Security-Policy-Report-Only
        value: default-src 'self'; img-src *; style-src 'self' 'unsafe-inline'; script-sr
        always: false
    reverse_proxy:
      locations:
        baobabservers:
          location: /
          proxy_pass: "http://baobabservers/VirtualHostBase/http/{{ inventory_hostname }}:80/VirtualHostRoot/"
      health_check_plus: false
    upstreams:
      baobabservers:
        name: baobabservers
        lb_method: least_conn
        zone_name: upstream_baobabservers
        zone_size: 64k
        sticky_cookie: false
        servers:
          baobab1:
            address: 127.0.0.1
            port: 8080
            weight: 1
            health_check: max_fails=1 fail_timeout=10s
          baobab2:
            address: 127.0.0.1
            port: 8081
            weight: 1
            health_check: max_fails=1 fail_timeout=10s                 