version: 2
jobs:
  build:
    docker:
      - image: ansible/ansible:ubuntu1604

    steps:
      - run:
          name: Install System Packages
          command: curl https://bootstrap.pypa.io/get-pip.py | python && pip install ansible

      - checkout

      - run:
          name: Syntax check
          command: ansible-playbook -i "localhost," site_test.yml --syntax-check
      
      - run:
          name: Run ansible-playbook
          command: ansible-playbook -i "localhost," site_test.yml -vvvv

workflows:
  version: 2
  build_test:
    jobs:
      - build
